name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.x"
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: rustfmt, clippy
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes shellcheck
      - name: Run portable tests
        run: |
          python3 -m unittest discover -s tests -p 'test_*.py'
          shellcheck worker-launcher.sh tests/run scripts/*.sh
          cargo fmt --all -- --check
          cargo clippy --all-targets -- -D warnings
          cargo test --locked --all-targets
